from __future__ import annotations

import json
import re
from dataclasses import dataclass
from typing import Any, Literal


@dataclass(frozen=True)
class ParsedMessage:
    kind: Literal["tool_call", "final"]
    name: str | None = None
    arguments: dict[str, Any] | None = None
    content: str | None = None


@dataclass(frozen=True)
class ParseError:
    raw: str
    reason: str


class ManualJsonProtocol:

    def build_system_prompt(
        self,
        tool_docs: str,
        skill_docs: str = "",
        memory_docs: str = "",
    ) -> str:
        return (
            "You are a coding assistant. Communicate ONLY in raw JSON. No markdown wrappers/intro/chat.\n\n"
            "=== SCHEMAS ===\n"
            '1. Tool Call: {"type":"tool_call","name":"<name>","arguments":{<args>}}\n'
            '2. Final Answer: {"type":"final","content":"<your_response>"}\n\n'
            "=== TOOLS ===\n"
            f"{tool_docs}\n\n"
            "=== SKILLS ===\n"
            "Load via `load_skill` before using logic:\n"
            f"{skill_docs}\n\n"
            "=== MEMORY ===\n"
            "Read/write via `read_memory`/`save_memory`:\n"
            f"{memory_docs}\n\n"
            "Remember: Minimize steps. Output exactly one JSON. When done, output 'final' immediately. No explanation."
        )

    def parse(self, text: str) -> ParsedMessage | ParseError:
        stripped = text.strip()

        # Try to find the first '{' and the last '}'
        start_idx = stripped.find("{")
        end_idx = stripped.rfind("}")

        if start_idx == -1 or end_idx == -1 or start_idx > end_idx:
            return ParseError(
                text,
                "No JSON object found in response. Your output must start with '{' and end with '}'.",
            )

        json_str = stripped[start_idx : end_idx + 1]

        # Replace smart/curly quotes which are sometimes hallucinatively generated by some models
        json_str = (
            json_str.replace("“", '"')
            .replace("”", '"')
            .replace("‘", "'")
            .replace("’", "'")
        )

        try:
            # strict=False allows literal control characters (e.g. unescaped newlines, tabs) in JSON string fields
            obj = json.loads(json_str, strict=False)
        except json.JSONDecodeError as e:
            return ParseError(text, f"Failed to parse JSON: {e}")

        match obj:
            case {"type": "tool_call", "name": str(name), "arguments": dict(args)}:
                return ParsedMessage(kind="tool_call", name=name, arguments=args)
            case {"type": "final", "content": str(content)}:
                return ParsedMessage(kind="final", content=content)
            case _:
                # Diagnostic fallback to return a detailed ParseError for repair
                if not isinstance(obj, dict):
                    return ParseError(
                        text, "Root element of JSON must be an object (dict)."
                    )
                if "type" not in obj:
                    return ParseError(text, "Missing 'type' field in JSON object.")

                msg_type = obj.get("type")
                if msg_type == "tool_call":
                    if "name" not in obj:
                        return ParseError(
                            text, "tool_call is missing the required 'name' field."
                        )
                    if not isinstance(obj["name"], str):
                        return ParseError(
                            text, "tool_call field 'name' must be a string."
                        )
                    if "arguments" not in obj:
                        return ParseError(
                            text, "tool_call is missing the required 'arguments' field."
                        )
                    if not isinstance(obj["arguments"], dict):
                        return ParseError(
                            text,
                            "tool_call field 'arguments' must be an object (dict).",
                        )
                elif msg_type == "final":
                    if "content" not in obj:
                        return ParseError(
                            text, "final is missing the required 'content' field."
                        )
                    if not isinstance(obj["content"], str):
                        return ParseError(
                            text, "final field 'content' must be a string."
                        )
                else:
                    if "arguments" in obj and isinstance(obj["arguments"], dict):
                        return ParsedMessage(
                            kind="tool_call", name=msg_type, arguments=obj["arguments"]
                        )
                    return ParseError(
                        text,
                        f"Unknown type '{msg_type}'. Must be 'tool_call' or 'final'.",
                    )

    def repair_prompt(self, bad_text: str, reason: str) -> str:
        return f"JSON Error: {reason}. Output ONLY raw JSON."
